server:
    port: 10086
debug: true
spring:
    devtools:
        restart:
            enabled: true #设置开启热部署
    freemaker:
        cache: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://41w9s30520.zicp.vip:15698/house?useUnicode = true&characterEncoding = utf-8&useSSL = false&serverTimezone=GMT%2B8
        username: root
        password: root

mybatis:
    #mapper配置文件
    mapper-locations: classpath:mapper/*.xml